language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pymongo==2.9
  - pip install mongo-orchestration==0.3.1
  - curl -O http://archive.apache.org/dist/lucene/solr/5.5.0/solr-5.5.0.tgz
  - tar -zxf solr-5.5.0.tgz
  - cd solr-5.5.0
  - bin/solr start
  - bin/solr create_core -c "mycore"
  - rm -f server/solr/mycore/conf/managed-schema
  - cp ../mongo_connector/doc_managers/schema.xml server/solr/mycore/conf/schema.xml
  - curl "http://localhost:8983/solr/admin/cores?action=RELOAD&core=mycore"
  - cd ..
  - export SOLR_URL='http://localhost:8983/solr/mycore'

before_script:
  - mongo-orchestration start

script:
  - python setup.py test

after_script:
  - mongo-orchestration stop
